Repository FRC2706/2019-2706-Robot-Code, pull requests merged in 2019-03, with the labels that each got.

#97 Config rework
  src/main/java/ca/team2706/frc/robot/OI.java
  src/main/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDrive.java
  src/main/java/ca/team2706/frc/robot/commands/drivebase/TankDrive.java
  src/main/java/ca/team2706/frc/robot/commands/drivebase/TankDriveWithJoystick.java
  src/main/java/ca/team2706/frc/robot/config/Config.java
  src/main/java/ca/team2706/frc/robot/config/XboxValue.java
  src/main/java/ca/team2706/frc/robot/input/FluidButton.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/MotionMagicTest.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/TankDriveTest.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/TankDriveWithJoystickTest.java
  src/test/java/ca/team2706/frc/robot/config/ConfigTest.java
  src/test/java/ca/team2706/frc/robot/config/FluidConstantTest.java
  src/test/java/ca/team2706/frc/robot/input/FluidButtonTest.java
Labels: bug, enhancement

#101 Fix motion magic control mode
  src/main/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDriveWithJoystick.java
  src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDriveWithJoystickTest.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/MotionMagicTest.java
Labels: bug

#99 Rcvi integration
  src/main/java/ca/team2706/frc/robot/OI.java
  src/main/java/ca/team2706/frc/robot/commands/drivebase/DriverAssistVision.java
  src/main/java/ca/team2706/frc/robot/config/Config.java
  src/main/java/ca/team2706/frc/robot/config/XboxValue.java
  src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
  src/test/java/ca/team2706/frc/robot/RobotTest.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDriveWithJoystickTest.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/DriverAssistVisionTest.java
  src/test/java/ca/team2706/frc/robot/config/ConfigTest.java
  src/test/java/ca/team2706/frc/robot/subsystems/DriveBaseTest.java
  vendordeps/PathfinderOLD.json
Labels: driver-assist, enhancement

#111 Absolute gyro rotation
  src/main/java/ca/team2706/frc/robot/OI.java
  src/main/java/ca/team2706/frc/robot/Robot.java
  src/main/java/ca/team2706/frc/robot/commands/drivebase/AbsoluteRotateWithGyro.java
  src/main/java/ca/team2706/frc/robot/commands/drivebase/RotateWithGyro.java
  src/main/java/ca/team2706/frc/robot/config/Config.java
  src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
  src/test/java/ca/team2706/frc/robot/RobotTest.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/AbsoluteRotateWithGyroTest.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/RotateWithGyroTest.java
Labels: enhancement

#94 Implemented basic functionality
  src/main/java/ca/team2706/frc/robot/OI.java
  src/main/java/ca/team2706/frc/robot/Robot.java
  src/main/java/ca/team2706/frc/robot/config/Config.java
  src/test/java/ca/team2706/frc/robot/RobotTest.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/TankDriveTest.java
Labels: enhancement

#112 Mechanisms
  src/main/java/ca/team2706/frc/robot/OI.java
  src/main/java/ca/team2706/frc/robot/Robot.java
  src/main/java/ca/team2706/frc/robot/commands/intake/AfterEjectConditional.java
  src/main/java/ca/team2706/frc/robot/commands/intake/EjectConditional.java
  src/main/java/ca/team2706/frc/robot/commands/intake/arms/LowerArms.java
  src/main/java/ca/team2706/frc/robot/commands/intake/arms/LowerArmsSafely.java
  src/main/java/ca/team2706/frc/robot/commands/intake/arms/MovePlunger.java
  src/main/java/ca/team2706/frc/robot/commands/intake/arms/RaiseArms.java
  src/main/java/ca/team2706/frc/robot/commands/intake/arms/RaiseArmsSafely.java
  src/main/java/ca/team2706/frc/robot/commands/intake/cargo/AutoEjectCargo.java
  src/main/java/ca/team2706/frc/robot/commands/intake/cargo/AutoIntakeCargo.java
  src/main/java/ca/team2706/frc/robot/commands/intake/cargo/RunIntakeAtSpeed.java
  src/main/java/ca/team2706/frc/robot/commands/intake/cargo/RunIntakeOnJoystick.java
  src/main/java/ca/team2706/frc/robot/commands/intake/hatch/AfterEjectHatch.java
  src/main/java/ca/team2706/frc/robot/commands/intake/hatch/EjectHatch.java
  src/main/java/ca/team2706/frc/robot/commands/lift/HoldLift.java
  src/main/java/ca/team2706/frc/robot/commands/lift/LiftPosition.java
  src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftJoystickVelocity.java
  src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftOnJoystick.java
  src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftOnOverride.java
  src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftToPosition.java
  src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftToSetpoint.java
  src/main/java/ca/team2706/frc/robot/commands/ringlight/ToggleRingLight.java
  src/main/java/ca/team2706/frc/robot/config/Config.java
  src/main/java/ca/team2706/frc/robot/input/EButton.java
  src/main/java/ca/team2706/frc/robot/input/FluidButton.java
  src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
  src/main/java/ca/team2706/frc/robot/subsystems/Intake.java
  src/main/java/ca/team2706/frc/robot/subsystems/Lift.java
  src/main/java/ca/team2706/frc/robot/subsystems/Pneumatics.java
  src/main/java/ca/team2706/frc/robot/subsystems/RingLight.java
  src/main/java/ca/team2706/frc/robot/subsystems/SensorExtras.java
  src/test/java/ca/team2706/frc/robot/RobotTest.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/DriverAssistVisionTest.java
  src/test/java/ca/team2706/frc/robot/config/ConfigTest.java
  src/test/java/ca/team2706/frc/robot/config/FluidConstantTest.java
  src/test/java/ca/team2706/frc/robot/input/EButtonTest.java
  src/test/java/ca/team2706/frc/robot/operatorfeedback/rumbler/RumblerTest.java
  src/test/java/util/Util.java
Labels: enhancement, mechanisms

#117 Lift setpoint changes
  src/main/java/ca/team2706/frc/robot/config/Config.java
  src/main/java/ca/team2706/frc/robot/subsystems/Lift.java
Labels: mechanisms

#119 Add timeout to EjectHatch
  src/main/java/ca/team2706/frc/robot/commands/intake/hatch/EjectHatch.java
Labels: mechanisms

#120 Adjust intake hatch lift speed
  src/main/java/ca/team2706/frc/robot/OI.java
Labels: mechanisms

#122 Build info
  build.gradle
  src/main/java/ca/team2706/frc/robot/Robot.java
  src/main/java/ca/team2706/frc/robot/logging/Log.java
  src/main/resources/log4j2.xml
Labels: enhancement

#139 Improve setpoint pov
  src/main/java/ca/team2706/frc/robot/OI.java
  src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftToSetpoint.java
  src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftToSetpointOnPOV.java
  src/main/java/ca/team2706/frc/robot/config/Config.java
  src/main/java/ca/team2706/frc/robot/input/ETrigger.java
  src/main/java/ca/team2706/frc/robot/input/FluidButton.java
  src/main/java/ca/team2706/frc/robot/input/FluidTrigger.java
Labels: enhancement

#140 Add check for if limit switch is enabled
  src/main/java/ca/team2706/frc/robot/subsystems/Lift.java
Labels: enhancement, mechanisms

#141 Fluid trigger lift override
  src/main/java/ca/team2706/frc/robot/OI.java
  src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftJoystickVelocity.java
  src/main/java/ca/team2706/frc/robot/commands/lift/MoveLiftOnJoystick.java
  src/main/java/ca/team2706/frc/robot/config/Config.java
  src/main/java/ca/team2706/frc/robot/input/FluidButton.java
Labels: enhancement, mechanisms

#146 Remove auto intake cargo, slow down intake
  src/main/java/ca/team2706/frc/robot/OI.java
  src/main/java/ca/team2706/frc/robot/commands/intake/cargo/RunIntakeOnJoystick.java
Labels: mechanisms

#123 Rcvi vision2
  src/main/java/ca/team2706/frc/robot/OI.java
  src/main/java/ca/team2706/frc/robot/SubsystemStatus.java
  src/main/java/ca/team2706/frc/robot/commands/drivebase/CurvatureDrive.java
  src/main/java/ca/team2706/frc/robot/commands/drivebase/DriverAssistVision.java
  src/main/java/ca/team2706/frc/robot/commands/drivebase/FollowTrajectory.java
  src/main/java/ca/team2706/frc/robot/commands/mirrorable/MirroredCommandGroup.java
  src/main/java/ca/team2706/frc/robot/config/Config.java
  src/main/java/ca/team2706/frc/robot/input/FluidButton.java
  src/main/java/ca/team2706/frc/robot/subsystems/DriveBase.java
  src/main/java/ca/team2706/frc/robot/subsystems/Pneumatics.java
  src/main/java/ca/team2706/frc/robot/subsystems/RingLight.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/DriverAssistVisionTest.java
  src/test/java/ca/team2706/frc/robot/commands/drivebase/MotionMagicVisionTest.java
  src/test/java/ca/team2706/frc/robot/config/ConfigTest.java
  src/test/java/ca/team2706/frc/robot/config/FluidConstantTest.java
  src/test/java/ca/team2706/frc/robot/subsystems/DriveBaseTest.java
Labels: driver-assist
